### PR TITLE
Shop Front

### PR DESCRIPTION
**Pull request by hazzargm**
The seed file is for testing purposes and is still in progress. Otherwise, just enhancements to the Shop Front view/edit pages.

### CODE REVIEW

**Comment by robwagner33** [comment]
You should add a .gitignore entry for the logs that solr generates.

**Comment by mccormjt** [comment]
I tried, look inside the got ignore, for some reason it's not working. Any ideas?

**Comment by robwagner33** [comment]
solr/development/data/index/**/*

**Comment by mccormjt** [comment]
Thanks Rob, I added that! What exactly does the "**/*" do?

**Comment by robwagner33** [comment]
```
folder/**/*
```
recursively searches through all of folders' subfolders (and their subfolders, etc.) and searches for * (everything). This is super useful when you want to find all of a specific file type in a directory tree
```
app/**/*.rb
```

**Comment by mccormjt** [comment]
nice thanks!
Also I just merged the shop_front branch with master and put all of the latest code in master on the test server so you guys can check it out live 😊

http://inventorswebmarketmastere4f0.ninefold-apps.com/

Cheers,
John

**Pull request merged**
